/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 4;
	int m = 3;
	int p = 10;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 0;
	x[1] = 0;
	x[2] = 0;
	x[3] = 0;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
		double a;
	_f[0] = 0.0;
	a = 0.55;
	_f[0] = 3*x1+1.0e-6*pow(x1,3)+2*x2+2.0e-6*pow(x2,3)/3;
	_h[0] = 1000*sin(-x3-0.25)+1000.0*sin(-x4-0.25)+894.8-x1;
	_h[1] = 1000*sin(x3-0.25)+1000.0*sin(x3-x4-0.25)+894.8-x2;
	_h[2] = 1000*sin(x4-0.25)+1000.0*sin(x4-x3-0.25)+1294.8;
	_g[0] = x3-x4-a;
	_g[1] = x4-x3-a;
	_g[2] = -x1;
	_g[3] = x1-1200;
	_g[4] = -x2;
	_g[5] = x2-1200;
	_g[6] = -a-x3;
	_g[7] = x3-a;
	_g[8] = -a-x4;
	_g[9] = x4-a;
	return;
}
