/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 2;
	int m = 0;
	int p = 7;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 90.0;
	x[1] = 10.0;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x2 = _x[1];
	double x1 = _x[0];
	_f[0] = 0.0;
	_f[0] = -75.196+3.8112*x1+0.0020567*x1*x1*x1-1.0345e-5*x1*x1*x1*x1+6.8306*x2-0.030234*x1*x2+1.28134e-3*x2*x1*x1+2.266e-7*x1*x1*x1*x1*x2-0.25645*x2*x2+0.0034604*x2*x2*x2-1.3514e-5*x2*x2*x2*x2+28.106/(x2+1.0)+5.2375e-6*x1*x1*x2*x2+6.3e-8*x1*x1*x1*x2*x2-7.0e-10*x1*x1*x1*x2*x2*x2-3.405e-4*x1*x2*x2+1.6638e-6*x1*x2*x2*x2+2.8673*exp(0.0005*x1*x2)-3.5256e-5*x1*x1*x1*x2;
	_g[0] = 700.0-x1*x2;
	_g[1] = x1*x1*0.008-x2;
	_g[2] = 5.0*(x1-55.0)-(x2-50.0)*(x2-50.0);
	_g[3] = -x1;
	_g[4] = x1-75.0;
	_g[5] = -x2;
	_g[6] = x2-65.0;
	return;
}
