/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 4;
	int m = 0;
	int p = 10;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 1;
	x[1] = 1;
	x[2] = 1;
	x[3] = 1;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	_f[0] = 0.0;
	_f[0] = 1+x1+x2+x3+x4;
	_g[0] = 4/x1+2.25/x2+1/x3+0.25/x4-0.0401;
	_g[1] = 0.16/x1+0.36/x2+0.64/x3+0.64/x4-0.010085;
	_g[2] = 0.001-x1;
	_g[3] = x1-4.0e5;
	_g[4] = 0.001-x2;
	_g[5] = x2-3.0e5;
	_g[6] = 0.001-x3;
	_g[7] = x3-2.0e5;
	_g[8] = 0.001-x4;
	_g[9] = x4-1.0e5;
	return;
}
