/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 15;
	int m = 0;
	int p = 59;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 20;
	x[1] = 55;
	x[2] = 15;
	x[3] = 20;
	x[4] = 60;
	x[5] = 20;
	x[6] = 20;
	x[7] = 60;
	x[8] = 20;
	x[9] = 20;
	x[10] = 60;
	x[11] = 20;
	x[12] = 20;
	x[13] = 60;
	x[14] = 20;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x15 = _x[14];
	double x14 = _x[13];
	double x9 = _x[8];
	double x13 = _x[12];
	double x8 = _x[7];
	double x12 = _x[11];
	double x7 = _x[6];
	double x11 = _x[10];
	double x6 = _x[5];
	double x10 = _x[9];
	double x5 = _x[4];
	double x4 = _x[3];
	_f[0] = 0.0;
	_f[0] = 2.3*x1+0.0001*x1*x1+1.7*x2+0.0001*x2*x2+2.2*x3+0.00015*x3*x3+2.3*x4+0.0001*x4*x4+1.7*x5+0.0001*x5*x5+2.2*x6+0.00015*x6*x6+2.3*x7+0.0001*x7*x7+1.7*x8+0.0001*x8*x8+2.2*x9+0.00015*x9*x9+2.3*x10+0.0001*x10*x10+1.7*x11+0.0001*x11*x11+2.2*x12+0.00015*x12*x12+2.3*x13+0.0001*x13*x13+1.7*x14+0.0001*x14*x14+2.2*x15+0.00015*x15*x15;
	_g[0] = (x4-x1+7.0-13.0);
	_g[1] = -(x4-x1+7.0);
	_g[2] = (x6-x3+7.0-13.0);
	_g[3] = -(x6-x3+7.0);
	_g[4] = (x5-x2+7.0-14.0);
	_g[5] = -(x5-x2+7.0);
	_g[6] = (x7-x4+7.0-13.0);
	_g[7] = -(x7-x4+7.0);
	_g[8] = (x9-x6+7.0-13.0);
	_g[9] = -(x9-x6+7.0);
	_g[10] = (x8-x5+7.0-14.0);
	_g[11] = -(x8-x5+7.0);
	_g[12] = (x10-x7+7.0-13.0);
	_g[13] = -(x10-x7+7.0);
	_g[14] = (x12-x9+7.0-13.0);
	_g[15] = -(x12-x9+7.0);
	_g[16] = (x11-x8+7.0-14.0);
	_g[17] = -(x11-x8+7.0);
	_g[18] = (x13-x10+7.0-13.0);
	_g[19] = -(x13-x10+7.0);
	_g[20] = (x15-x12+7.0-13.0);
	_g[21] = -(x15-x12+7.0);
	_g[22] = (x14-x11+7.0-14.0);
	_g[23] = -(x14-x11+7.0);
	_g[24] = 60.0-x1-x2-x3;
	_g[25] = 70.0-x7-x8-x9;
	_g[26] = 100.0-x13-x14-x15;
	_g[27] = 50.0-x4-x5-x6;
	_g[28] = 85.0-x10-x11-x12;
	_g[29] = 8.0-x1;
	_g[30] = 43.0-x2;
	_g[31] = 3.0-x3;
	_g[32] = x1-21.0;
	_g[33] = x2-57.0;
	_g[34] = x3-16.0;
	_g[35] = x4-90.0;
	_g[36] = -x4;
	_g[37] = x5-120.0;
	_g[38] = -x5;
	_g[39] = x6-60.0;
	_g[40] = -x6;
	_g[41] = x7-90.0;
	_g[42] = -x7;
	_g[43] = x8-120.0;
	_g[44] = -x8;
	_g[45] = x9-60.0;
	_g[46] = -x9;
	_g[47] = x10-90.0;
	_g[48] = -x10;
	_g[49] = x11-120.0;
	_g[50] = -x11;
	_g[51] = x12-60.0;
	_g[52] = -x12;
	_g[53] = x13-90.0;
	_g[54] = -x13;
	_g[55] = x14-120.0;
	_g[56] = -x14;
	_g[57] = x15-60.0;
	_g[58] = -x15;
	return;
}
