/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 10;
	int m = 3;
	int p = 28;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 1745.0;
	x[1] = 12000.0;
	x[2] = 110.0;
	x[3] = 3048.0;
	x[4] = 1974.0;
	x[5] = 89.2;
	x[6] = 92.8;
	x[7] = 8.0;
	x[8] = 3.6;
	x[9] = 145.0;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x9 = _x[8];
	double x8 = _x[7];
	double x7 = _x[6];
	double x6 = _x[5];
	double x10 = _x[9];
	double x5 = _x[4];
	double x4 = _x[3];
		double b;
		double a;
	_f[0] = 0.0;
	a = 0.99;
	b = 0.9;
	_f[0] = 5.04*x1+0.035*x2+10.0*x3+3.36*x5-0.063*x4*x7;
	_h[0] = 1.22*x4-x1-x5;
	_h[1] = 98000.0*x3/(x4*x9+1000.0*x3)-x6;
	_h[2] = (x2+x5)/x1-x8;
	_g[0] = 0.222*x10+b*x9-35.82;
	_g[1] = a*x10+133.0-3.0*x7;
	_g[2] = -(0.222*x10+b*x9-35.82)-x9*((1.0/b)-b);
	_g[3] = -(a*x10+133.0-3.0*x7)-((1.0/a)-a)*x10;
	_g[4] = a*x4+0.00667*x1*x8*x8-0.13167*x1*x8-1.12*x1;
	_g[5] = a*x7-0.325*x6+0.038*x8*x8-1.098*x8-57.425;
	_g[6] = -(a*x4+0.00667*x1*x8*x8-0.13167*x1*x8-1.12*x1)-((1.0/a)-a)*x4;
	_g[7] = -(a*x7-0.325*x6+0.038*x8*x8-1.098*x8-57.425)-((1.0/a)-a)*x7;
	_g[8] = 0.00001-x1;
	_g[9] = 0.00001-x2;
	_g[10] = 0.00001-x3;
	_g[11] = 0.00001-x4;
	_g[12] = 0.00001-x5;
	_g[13] = 85.0-x6;
	_g[14] = 90.0-x7;
	_g[15] = 3.0-x8;
	_g[16] = 1.2-x9;
	_g[17] = 145.0-x10;
	_g[18] = x1-2000.0;
	_g[19] = x2-16000.0;
	_g[20] = x3-120.0;
	_g[21] = x4-5000.0;
	_g[22] = x5-2000.0;
	_g[23] = x6-93.0;
	_g[24] = x7-95.0;
	_g[25] = x8-12.0;
	_g[26] = x9-4.0;
	_g[27] = x10-162.0;
	return;
}
