/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 8;
	int m = 0;
	int p = 22;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 5000;
	x[1] = 5000;
	x[2] = 5000;
	x[3] = 200;
	x[4] = 350;
	x[5] = 150;
	x[6] = 225;
	x[7] = 425;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x8 = _x[7];
	double x7 = _x[6];
	double x6 = _x[5];
	double x5 = _x[4];
	_f[0] = 0.0;
	_f[0] = x1+x2+x3;
	_g[0] = 0.0025*(x4+x6)-1;
	_g[1] = 0.0025*(x5+x7-x4)-1;
	_g[2] = 0.01*(x8-x5)-1;
	_g[3] = 100*x1+833.33252*x4-x1*x6-83333.333;
	_g[4] = 1250*x5+x2*x4-1250*x4-x2*x7;
	_g[5] = 1250000+x3*x5-2500*x5-x3*x8;
	_g[6] = 100-x1;
	_g[7] = x1-10000;
	_g[8] = 1000-x2;
	_g[9] = x2-10000;
	_g[10] = 1000-x3;
	_g[11] = x3-10000;
	_g[12] = 10-x4;
	_g[13] = x4-1000;
	_g[14] = 10-x5;
	_g[15] = x5-1000;
	_g[16] = 10-x6;
	_g[17] = x6-1000;
	_g[18] = 10-x7;
	_g[19] = x7-1000;
	_g[20] = 10-x8;
	_g[21] = x8-1000;
	return;
}
