/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 13;
	int m = 0;
	int p = 41;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 0.5;
	x[1] = 0.8;
	x[2] = 0.9;
	x[3] = 0.1;
	x[4] = 0.14;
	x[5] = 0.5;
	x[6] = 489;
	x[7] = 80;
	x[8] = 650;
	x[9] = 450;
	x[10] = 150;
	x[11] = 150;
	x[12] = 150;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x9 = _x[8];
	double x13 = _x[12];
	double x8 = _x[7];
	double x12 = _x[11];
	double x7 = _x[6];
	double x11 = _x[10];
	double x6 = _x[5];
	double x10 = _x[9];
	double x5 = _x[4];
	double x4 = _x[3];
	_f[0] = 0.0;
	_f[0] = x11+x12+x13;
	_g[0] = x2-x3;
	_g[1] = x1-x2;
	_g[2] = 0.002*x7-0.002*x8-1;
	_g[3] = 1.262626*x10-1.231059*x3*x10-x13;
	_g[4] = 1.262626*x8-1.231059*x1*x8-x11;
	_g[5] = 1.262626*x9-1.231059*x2*x9-x12;
	_g[6] = 0.03475*x2+0.975*x2*x5-0.00975*x2*x2-x5;
	_g[7] = 0.03475*x3+0.975*x3*x6-0.00975*x3*x3-x6;
	_g[8] = 0.03475*x1+0.975*x1*x4-0.00975*x1*x1-x4;
	_g[9] = x1*x8+x4*x7-x4*x8-x5*x7;
	_g[10] = 0.002*(x2*x9+x5*x8-x1*x8-x6*x9)+x5+x6-1;
	_g[11] = 0.9+0.002*(x2*x10-x3*x10)-x2;
	_g[12] = x3*x10+x6*x9+500*x2-500*x6-x2*x10-x2*x9;
	_g[13] = 50-x11-x12-x13;
	_g[14] = x11+x12+x13-250;
	_g[15] = 0.1-x1;
	_g[16] = x1-1;
	_g[17] = 0.1-x2;
	_g[18] = x2-1;
	_g[19] = 0.1-x3;
	_g[20] = x3-1;
	_g[21] = 0.0001-x4;
	_g[22] = x4-0.1;
	_g[23] = 0.1-x5;
	_g[24] = x5-0.9;
	_g[25] = 0.1-x6;
	_g[26] = x6-0.9;
	_g[27] = 0.1-x7;
	_g[28] = x7-1000;
	_g[29] = 0.1-x8;
	_g[30] = x8-1000;
	_g[31] = 500-x9;
	_g[32] = x9-1000;
	_g[33] = 0.1-x10;
	_g[34] = x10-500;
	_g[35] = 1-x11;
	_g[36] = x11-150;
	_g[37] = 0.0001-x12;
	_g[38] = x12-150;
	_g[39] = 0.0001-x13;
	_g[40] = x13-150;
	return;
}
