/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 7;
	int m = 0;
	int p = 20;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 6;
	x[1] = 6;
	x[2] = 6;
	x[3] = 6;
	x[4] = 6;
	x[5] = 6;
	x[6] = 6;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x7 = _x[6];
	double x6 = _x[5];
	double x5 = _x[4];
		double a;
	_f[0] = 0.0;
	a = 0.5;
	_f[0] = 10*x1*pow(x2,-1)*pow(x4,2)*pow(x6,-3)*pow(x7,a)+15*pow(x1,-1)*pow(x2,-2)*x3*x4*pow(x5,-1)*pow(x7,-0.5)+20*pow(x1,-2)*x2*pow(x4,-1)*pow(x5,-2)*x6+25*pow(x1,2)*pow(x2,2)*pow(x3,-1)*pow(x5,0.5)*pow(x6,-2)*x7;
	_g[0] = 0.5*pow(x1,0.5)*pow(x3,-1)*pow(x6,-2)*x7+0.7*pow(x1,3)*x2*pow(x3,-2)*x6*pow(x7,0.5)+0.2*pow(x2,-1)*x3*pow(x4,-0.5)*pow(x6,(2.0/3.0))*pow(x7,0.25)-1;
	_g[1] = 1.3*pow(x1,-0.5)*x2*pow(x3,-1)*pow(x5,-1)*x6+0.8*x3*pow(x4,-1)*pow(x5,-1)*pow(x6,2)+3.1*pow(x1,-1)*pow(x2,0.5)*pow(x4,-2)*pow(x5,-1)*pow(x6,(1.0/3.0))-1;
	_g[2] = 2*x1*pow(x3,-1.5)*x5*pow(x6,-1)*pow(x7,(1.0/3.0))+0.1*x2*pow(x3,-0.5)*x5*pow(x6,-1)*pow(x7,-0.5)+pow(x1,-1)*x2*pow(x3,0.5)*x5+0.65*pow(x2,-2)*x3*x5*pow(x6,-1)*x7-1;
	_g[3] = 0.2*pow(x1,-2)*x2*pow(x4,-1)*pow(x5,0.5)*pow(x7,(1.0/3.0))+0.3*pow(x1,0.5)*pow(x2,2)*x3*pow(x4,(1.0/3.0))*pow(x7,0.25)*pow(x5,(-2.0/3.0))+0.4*pow(x1,-3)*pow(x2,-2)*x3*x5*pow(x7,0.75)+0.5*pow(x3,-2)*x4*pow(x7,0.5)-1;
	_g[4] = 100-(10*x1*pow(x2,-1)*pow(x4,2)*pow(x6,-3)*pow(x7,a)+15*pow(x1,-1)*pow(x2,-2)*x3*x4*pow(x5,-1)*pow(x7,-0.5)+20*pow(x1,-2)*x2*pow(x4,-1)*pow(x5,-2)*x6+25*pow(x1,2)*pow(x2,2)*pow(x3,-1)*pow(x5,0.5)*pow(x6,-2)*x7);
	_g[5] = 10*x1*pow(x2,-1)*pow(x4,2)*pow(x6,-3)*pow(x7,a)+15*pow(x1,-1)*pow(x2,-2)*x3*x4*pow(x5,-1)*pow(x7,-0.5)+20*pow(x1,-2)*x2*pow(x4,-1)*pow(x5,-2)*x6+25*pow(x1,2)*pow(x2,2)*pow(x3,-1)*pow(x5,0.5)*pow(x6,-2)*x7-3000;
	_g[6] = 0.1-x1;
	_g[7] = x1-10;
	_g[8] = 0.1-x2;
	_g[9] = x2-10;
	_g[10] = 0.1-x3;
	_g[11] = x3-10;
	_g[12] = 0.1-x4;
	_g[13] = x4-10;
	_g[14] = 0.1-x5;
	_g[15] = x5-10;
	_g[16] = 0.1-x6;
	_g[17] = x6-10;
	_g[18] = 0.01-x7;
	_g[19] = x7-10;
	return;
}
