/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 8;
	int m = 0;
	int p = 22;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 6;
	x[1] = 3;
	x[2] = 0.4;
	x[3] = 0.2;
	x[4] = 6;
	x[5] = 6;
	x[6] = 1;
	x[7] = 0.5;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x8 = _x[7];
	double x7 = _x[6];
	double x6 = _x[5];
	double x5 = _x[4];
	_f[0] = 0.0;
	_f[0] = 0.4*pow(x1,0.67)*pow(x7,-0.67)+0.4*pow(x2,0.67)*pow(x8,-0.67)+10-x1-x2;
	_g[0] = 0.1*x1+0.0588*x5*x7-1;
	_g[1] = 0.1*x1+0.1*x2+0.0588*x6*x8-1;
	_g[2] = 4*x3*pow(x5,-1)+2*pow(x3,-0.71)*pow(x5,-1)+0.0588*pow(x3,-1.3)*x7-1;
	_g[3] = 4*x4*pow(x6,-1)+2*pow(x4,-0.71)*pow(x6,-1)+0.0588*pow(x4,-1.3)*x8-1;
	_g[4] = 1-(0.4*pow(x1,0.67)*pow(x7,-0.67)+0.4*pow(x2,0.67)*pow(x8,-0.67)+10-x1-x2);
	_g[5] = 0.4*pow(x1,0.67)*pow(x7,-0.67)+0.4*pow(x2,0.67)*pow(x8,-0.67)+10-x1-x2-4.2;
	_g[6] = 0.1-x1;
	_g[7] = x1-10;
	_g[8] = 0.1-x2;
	_g[9] = x2-10;
	_g[10] = 0.1-x3;
	_g[11] = x3-10;
	_g[12] = 0.1-x4;
	_g[13] = x4-10;
	_g[14] = 0.1-x5;
	_g[15] = x5-10;
	_g[16] = 0.1-x6;
	_g[17] = x6-10;
	_g[18] = 0.1-x7;
	_g[19] = x7-10;
	_g[20] = 0.1-x8;
	_g[21] = x8-10;
	return;
}
