/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 10;
	int m = 3;
	int p = 20;
	x = (double *)calloc(n, sizeof(double));
	x[0] = -2.3;
	x[1] = -2.3;
	x[2] = -2.3;
	x[3] = -2.3;
	x[4] = -2.3;
	x[5] = -2.3;
	x[6] = -2.3;
	x[7] = -2.3;
	x[8] = -2.3;
	x[9] = -2.3;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x9 = _x[8];
	double x8 = _x[7];
	double x7 = _x[6];
	double x6 = _x[5];
	double x10 = _x[9];
	double x5 = _x[4];
	double x4 = _x[3];
		double c9;
		double c8;
		double c7;
		double c6;
		double c5;
		double c4;
		double c3;
		double c10;
		double c2;
		double c1;
	_f[0] = 0.0;
    c1 = -6.089;
    c2 = -17.164;
    c3 = -34.054;
    c4 = -5.914;
    c5 = -24.721;
    c6 = -14.986;
    c7 = -24.100;
    c8 = -10.708;
    c9 = -26.662;
    c10 = -22.179;
	_f[0] = exp(x1)*(c1+x1-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x2)*(c2+x2-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x3)*(c3+x3-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x4)*(c4+x4-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x5)*(c5+x5-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x6)*(c6+x6-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x7)*(c7+x7-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x8)*(c8+x8-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x9)*(c9+x9-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)))+exp(x10)*(c10+x10-log(exp(x1)+exp(x2)+exp(x3)+exp(x4)+exp(x5)+exp(x6)+exp(x7)+exp(x8)+exp(x9)+exp(10)));
	_h[0] = exp(x1)+2.0*exp(x2)+2.0*exp(x3)+exp(x6)+exp(x10)-2.0;
	_h[1] = exp(x4)+2.0*exp(x5)+exp(x6)+exp(x7)-1.0;
	_h[2] = exp(x3)+exp(x7)+exp(x8)+2.0*exp(x9)+exp(x10)-1.0;
	_g[0] = -100.0-x1;
	_g[1] = -100.0-x2;
	_g[2] = -100.0-x3;
	_g[3] = -100.0-x4;
	_g[4] = -100.0-x5;
	_g[5] = -100.0-x6;
	_g[6] = -100.0-x7;
	_g[7] = -100.0-x8;
	_g[8] = -100.0-x9;
	_g[9] = -100.0-x10;
	_g[10] = x1-100.0;
	_g[11] = x2-100.0;
	_g[12] = x3-100.0;
	_g[13] = x4-100.0;
	_g[14] = x5-100.0;
	_g[15] = x6-100.0;
	_g[16] = x7-100.0;
	_g[17] = x8-100.0;
	_g[18] = x9-100.0;
	_g[19] = x10-100.0;
	return;
}
