/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 7;
	int m = 2;
	int p = 14;
	x = (double *)calloc(n, sizeof(double));
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x7 = _x[6];
	double x6 = _x[5];
	double x5 = _x[4];
		double s5;
		double s4;
		double s3;
		double s2;
		double s1;
		double q8;
		double q7;
		double q6;
		double q5;
		double q4;
		double q3;
		double q2;
		double q1;
		double r8;
		double r7;
		double r6;
		double r5;
		double r4;
		double r3;
		double r2;
		double r1;
		double b;
		double s8;
		double s7;
		double s6;
	_f[0] = 0.0;
		b = 32.0 ;
		r1 = 0.0 ;
		q1 = 0.0 ;
		s1 = 0.0 ;
		r2=50.0*25.0*cos(x1)+r1 ;
		r3=50.0*25.0*cos(x2)+r2 ;
		r4=75.0*50.0*cos(x3)+r3 ;
		r5=75.0*50.0*cos(x4)+r4 ;
		r6=75.0*50.0*cos(x5)+r5 ;
		r7=100.0*90.0*cos(x6)+r6 ;
		r8=100.0*90.0*cos(x7)+r7 ;
		q2=0.5*25.0*25.0*(50.0*sin(x1)-b)+25.0*s1+q1 ;
		s2=25.0*(50.0*sin(x1)-b)+s1 ;
		q3=0.5*25.0*25.0*(50.0*sin(x2)-b)+25.0*s2+q2 ;
		s3=25.0*(50.0*sin(x2)-b)+s2 ;
		q4=0.5*50.0*50.0*(75.0*sin(x3)-b)+50.0*s3+q3 ;
		s4=50.0*(75.0*sin(x3)-b)+s3 ;
		q5=0.5*50.0*(150.0-100.0)*(75.0*sin(x4)-b)+50.0*s4+q4 ;
		s5=50.0*(75.0*sin(x4)-b)+s4 ;
		q6=0.5*50.0*50.0*(75.0*sin(x5)-b)+50.0*s5+q5 ;
		s6=50.0*(75.0*sin(x5)-b)+s5 ;
		q7=0.5*90.0*90.0*(100.0*sin(x6)-b)+90.0*s6+q6 ;
		s7=90.0*(100.0*sin(x6)-b)+s6 ;
		q8=0.5*90.0*90.0*(100.0*sin(x7)-b)+90.0*s7+q7 ;
		s8=90.0*(100.0*sin(x7)-b)+s7 	;
	_f[0] = -r8*r8;
	_h[0] = q8-1.0e5;
	_h[1] = s8-1.0e3;
	_g[0] = -x1;
	_g[1] = x1-1.58;
	_g[2] = -x2;
	_g[3] = x2-1.58;
	_g[4] = -x3;
	_g[5] = x3-1.58;
	_g[6] = -x4;
	_g[7] = x4-1.58;
	_g[8] = -x5;
	_g[9] = x5-1.58;
	_g[10] = -x6;
	_g[11] = x6-1.58;
	_g[12] = -x7;
	_g[13] = x7-1.58;
	return;
}
