/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 3;
	int m = 0;
	int p = 7;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 4.5;
	x[1] = 4.5;
	x[2] = 5;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	_f[0] = 0.0;
	_f[0] = pow((x1-x2),2)+0.1111111*pow((x1+x2-10),2)+pow((x3-5),2);
	_g[0] = x1*x1+x2*x2+x3*x3-48;
	_g[1] = -4.5-x1;
	_g[2] = x1-4.5;
	_g[3] = -4.5-x2;
	_g[4] = x2-4.5;
	_g[5] = -5-x3;
	_g[6] = x3-5;
	return;
}
