/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 3;
	int m = 0;
	int p = 8;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 0;
	x[1] = 1.05;
	x[2] = 2.9;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	_f[0] = 0.0;
	_f[0] = 0.2*x3-0.8*x1;
	_g[0] = exp(x1)-x2;
	_g[1] = exp(x2)-x3;
	_g[2] = -x1;
	_g[3] = x1-100;
	_g[4] = -x2;
	_g[5] = x2-100;
	_g[6] = -x3;
	_g[7] = x3-10;
	return;
}
