/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 5;
	int m = 0;
	int p = 16;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 78;
	x[1] = 33;
	x[2] = 27;
	x[3] = 27;
	x[4] = 27;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x5 = _x[4];
		double a3;
		double a2;
		double a1;
		double a9;
		double a8;
		double a12;
		double a7;
		double a11;
		double a6;
		double a10;
		double a5;
		double a4;
	_f[0] = 0.0;
	a1 = 85.334407;
	a2 = 0.0056858;
	a3 = 0.0006262;
	a4 = 0.0022053;
	a5 = 80.51249;
	a6 = 0.0071317;
	a7 = 0.0029955;
	a8 = 0.0021813;
	a9 = 9.300961;
	a10 = 0.0047026;
	a11 = 0.0012547;
	a12 = 0.0019085;
	_f[0] = 5.3578547*x3*x3+0.8356891*x1*x5+37.293239*x1-40792.141;
	_g[0] = a1+a2*x2*x5+a3*x1*x4-a4*x3*x5-92;
	_g[1] = a5+a6*x2*x5+a7*x1*x2+a8*x3*x3-90-20;
	_g[2] = a9+a10*x3*x5+a11*x1*x3+a12*x3*x4-20-5;
	_g[3] = -(a1+a2*x2*x5+a3*x1*x4-a4*x3*x5);
	_g[4] = -(a5+a6*x2*x5+a7*x1*x2+a8*x3*x3-90);
	_g[5] = -(a9+a10*x3*x5+a11*x1*x3+a12*x3*x4-20);
	_g[6] = 78-x1;
	_g[7] = x1-102;
	_g[8] = 33-x2;
	_g[9] = x2-45;
	_g[10] = 27-x3;
	_g[11] = x3-45;
	_g[12] = 27-x4;
	_g[13] = x4-45;
	_g[14] = 27-x5;
	_g[15] = x5-45;
	return;
}
