/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 6;
	int m = 0;
	int p = 16;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 0;
	x[1] = 0;
	x[2] = 0;
	x[3] = 0;
	x[4] = 0;
	x[5] = 0;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x6 = _x[5];
	double x5 = _x[4];
		double b4;
		double b3;
		double b2;
		double b1;
	_f[0] = 0.0;
	b1 = 32.97;
	b2 = 25.12;
	b3 = -124.08;
	b4 = -173.02;
	_f[0] = 4.3*x1+31.8*x2+63.3*x3+15.8*x4+68.5*x5+4.7*x6;
	_g[0] = b1-17.1*x1-38.2*x2-204.2*x3-212.3*x4-623.4*x5-1495.5*x6+169*x1*x3+3580*x3*x5+3810*x4*x5+18500*x4*x6+24300*x5*x6;
	_g[1] = b2-17.9*x1-36.8*x2-113.9*x3-169.7*x4-337.8*x5-1385.2*x6+139*x1*x3+2450*x4*x5+16600*x4*x6+17200*x5*x6;
	_g[2] = b3+273*x2+70*x4+819*x5-26000*x4*x5;
	_g[3] = b4-159.9*x1+311*x2-587*x4-391*x5-2198*x6+14000*x1*x6;
	_g[4] = -x1;
	_g[5] = x1-0.31;
	_g[6] = -x2;
	_g[7] = x2-0.046;
	_g[8] = -x3;
	_g[9] = x3-0.068;
	_g[10] = -x4;
	_g[11] = x4-0.042;
	_g[12] = -x5;
	_g[13] = x5-0.028;
	_g[14] = -x6;
	_g[15] = x6-0.0134;
	return;
}
