/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 2;
	int m = 1;
	int p = 0;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 0.01;
	x[1] = 0.1;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x2 = _x[1];
	double x1 = _x[0];
	_f[0] = 0.0;
	_f[0] = 0.5*pow(x2,2)-x1*x2+(1.0/(6.0*pow(1-x2,3)))*(-4.0*pow(x2-x1,3)-6*(x1-x2*x2)*pow(x2-x1,2)-12*(x2-x1)*pow(x1-x2*x2,2)-17*pow(x1-x2*x2,3)+3*pow(x1-x2*x2,4)/(1-x2));
	_h[0] = x1+(1.0/(1-x2*x2))*(pow(x2-x1,2)+(x2-x1)*pow(x1-x2,2)+2.0*pow(x1-x2*x2,2));
	return;
}
