/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 7;
	int m = 0;
	int p = 4;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 1;
	x[1] = 2;
	x[2] = 0;
	x[3] = 4;
	x[4] = 0;
	x[5] = 1;
	x[6] = 1;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x7 = _x[6];
	double x6 = _x[5];
	double x5 = _x[4];
	_f[0] = 0.0;
	_f[0] = pow((x1-10),2)+5*pow((x2-12),2)+pow(x3,4)+3*pow((x4-11),2)+10*pow(x5,6)+7*pow(x6,2)+pow(x7,4)-4*x6*x7-10*x6-8*x7;
	_g[0] = 5*x5+4*pow(x4,2)+x3+3*pow(x2,4)+2*pow(x1,2)-127;
	_g[1] = 7*x1+3*x2+10*pow(x3,2)+x4-x5-282;
	_g[2] = 23*x1+pow(x2,2)+6*pow(x6,2)-8*x7-196;
	_g[3] = 4*pow(x1,2)+pow(x2,2)-3*x1*x2+2*pow(x3,2)+5*x6-11*x7;
	return;
}
