/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 10;
	int m = 3;
	int p = 10;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 0.1;
	x[1] = 0.1;
	x[2] = 0.1;
	x[3] = 0.1;
	x[4] = 0.1;
	x[5] = 0.1;
	x[6] = 0.1;
	x[7] = 0.1;
	x[8] = 0.1;
	x[9] = 0.1;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x9 = _x[8];
	double x8 = _x[7];
	double x7 = _x[6];
	double x6 = _x[5];
	double x10 = _x[9];
	double x5 = _x[4];
	double x4 = _x[3];
		double c9;
		double c8;
		double c7;
		double c6;
		double c5;
		double c4;
		double c3;
		double c10;
		double c2;
		double c1;
	_f[0] = 0.0;
    c1 = -6.089;
    c2 = -17.164;
    c3 = -34.054;
    c4 = -5.914;
    c5 = -24.721;
    c6 = -14.986;
    c7 = -24.100;
    c8 = -10.708;
    c9 = -26.662;
    c10 = -22.179;
	_f[0] = x1*(c1+log(x1/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x2*(c2+log(x2/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x3*(c3+log(x3/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x4*(c4+log(x4/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x5*(c5+log(x5/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x6*(c6+log(x6/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x7*(c7+log(x7/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x8*(c8+log(x8/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x9*(c9+log(x9/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)))+x10*(c10+log(x10/(x1+x2+x3+x4+x5+x6+x7+x8+x9+x10)));
	_h[0] = x1+2.0*x2+2.0*x3+x6+x10-2.0;
	_h[1] = x4+2.0*x5+x6+x7-1.0;
	_h[2] = x3+x7+x8+2.0*x9+x10-1.0;
	_g[0] = -x1;
	_g[1] = -x2;
	_g[2] = -x3;
	_g[3] = -x4;
	_g[4] = -x5;
	_g[5] = -x6;
	_g[6] = -x7;
	_g[7] = -x8;
	_g[8] = -x9;
	_g[9] = -x10;
	return;
}
