/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 3;
	int m = 2;
	int p = 0;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 4;
	x[1] = -3;
	x[2] = 4;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	_f[0] = 0.0;
	_f[0] = 4*pow(x1,2)+2*pow(x2,2)+2*pow(x3,2)-33*x1+16*x2-24*x3;
	_h[0] = 2*pow(x2,2)+3*x1-7;
	_h[1] = pow(x3,2)+4*x1-11;
	return;
}
