/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 9;
	int m = 6;
	int p = 20;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 0;
	x[1] = 0;
	x[2] = 0;
	x[3] = 0;
	x[4] = 0;
	x[5] = 0;
	x[6] = 0;
	x[7] = 0;
	x[8] = 0;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x9 = _x[8];
	double x8 = _x[7];
	double x7 = _x[6];
	double x6 = _x[5];
	double x5 = _x[4];
	double x4 = _x[3];
		double b;
		double a;
		double c;
	_f[0] = 0.0;
	a = 50.176;
	b = sin(0.25);
	c = cos(0.25);
	_f[0] = 3*x1+1.0e-6*x1*x1*x1+2.0*x2+0.522074e-6*x2*x2*x2;
	_h[0] = 400*a-a*x1+2*b*x5*x5+x5*x7*sin(-x4-0.25)+x5*x6*sin(-x3-0.25);
	_h[1] = 400*a-a*x2+2*b*x6*x6+x6*x7*sin(x3-x4-0.25)+x5*x6*sin(x3-0.25);
	_h[2] = 881.779*a+2*b*x7*x7+x6*x7*sin(x4-x3-0.25)+x5*x7*sin(x4-0.25);
	_h[3] = a*x8+x5*x6*cos(-x3-0.25)+x5*x7*cos(-x4-0.25)-200*a-2*c*x5*x5+0.7533e-3*a*x5*x5;
	_h[4] = a*x9+x5*x6*cos(x3-0.25)+x6*x7*cos(x3-x4-0.25)-200*a-2*c*x6*x6+0.7533e-3*a*x6*x6;
	_h[5] = x5*x7*cos(x4-0.25)+x6*x7*cos(x4-x3-0.25)+22.938*a-2*c*x7*x7+0.7533e-3*a*x7*x7;
	_g[0] = x3-x4-0.55;
	_g[1] = x4-x3-0.55;
	_g[2] = x1*x1+x8*x8-2250000;
	_g[3] = x2*x2+x9*x9-2250000;
	_g[4] = -x1;
	_g[5] = -x2;
	_g[6] = -0.55-x3;
	_g[7] = x3-0.55;
	_g[8] = -0.55-x4;
	_g[9] = x4-0.55;
	_g[10] = 196-x5;
	_g[11] = x3-252;
	_g[12] = 196-x6;
	_g[13] = x6-252;
	_g[14] = 196-x7;
	_g[15] = x7-252;
	_g[16] = -400-x8;
	_g[17] = x8-800;
	_g[18] = -400-x9;
	_g[19] = x9-800;
	return;
}
