/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 6;
	int m = 6;
	int p = 8;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 1;
	x[1] = 2;
	x[2] = 0;
	x[3] = 0;
	x[4] = 0;
	x[5] = 2;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x6 = _x[5];
	double x5 = _x[4];
	_f[0] = 0.0;
	_f[0] = x1+2*x2+4*x5+exp(x1*x4);
	_h[0] = x1+2*x2+5*x5-6;
	_h[1] = x1+x2+x3-3;
	_h[2] = x4+x5+x6-2;
	_h[3] = x1+x4-1;
	_h[4] = x2+x5-2;
	_h[5] = x3+x6-2;
	_g[0] = -x1;
	_g[1] = x1-1;
	_g[2] = -x2;
	_g[3] = -x3;
	_g[4] = -x4;
	_g[5] = x4-1;
	_g[6] = -x5;
	_g[7] = -x6;
	return;
}
