/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 2;
	int m = 0;
	int p = 6;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 20.1;
	x[1] = 5.84;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x2 = _x[1];
	double x1 = _x[0];
	_f[0] = 0.0;
	_f[0] = pow((x1-10),3)+pow((x2-20),3);
	_g[0] = 100.0-(x1-5.0)*(x1-5.0)-(x2-5.0)*(x2-5.0);
	_g[1] = (x1-6.0)*(x1-6.0)+(x2-5.0)*(x2-5.0)-82.81;
	_g[2] = 13-x1;
	_g[3] = x1-100;
	_g[4] = -x2;
	_g[5] = x2-100;
	return;
}
