/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 6;
	int m = 1;
	int p = 12;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 6.0e3;
	x[1] = 1.5;
	x[2] = 4.0e6;
	x[3] = 2.0;
	x[4] = 3.0e-3;
	x[5] = 5.0e7;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x6 = _x[5];
	double x5 = _x[4];
		double r;
		double s6;
		double s5;
		double s4;
		double m6;
		double s3;
		double m5;
		double s2;
		double m4;
		double s1;
		double m3;
		double m2;
		double m1;
	_f[0] = 0.0;
	m1 = 10000;
	m2 = 1;
	m3 = 2.0e6;
	m4 = 10;
	m5 = 0.001;
	m6 = 1.0e8;
	s1 = 8000;
	s2 = 1;
	s3 = 7.0e6;
	s4 = 50;
	s5 = 0.05;
	s6 = 5.0e8;
	r = 0.2;
	_f[0] = -exp((((1/(1-r*r))*((x1-m1)*(x1-m1)/(s1*s1)+2*r*(x1-m1)*(x2-m2)/(s1*s2)+(x2-m2)*(x2-m2)/(s2*s2)))+(x3-m3)*(x3-m3)/(s3*s3)+(x4-m4)*(x4-m4)/(s4*s4)+(x5-m5)*(x5-m5)/(s5*s5)+(x6-m6)*(x6-m6)/(s6*s6))/(-2));
	_h[0] = x1-m1-0.2*s1+4000*(x2-m2)-2000*s2;
	_g[0] = -x1;
	_g[1] = x1-2.0e4;
	_g[2] = -10-x2;
	_g[3] = x2-10;
	_g[4] = -x3;
	_g[5] = x3-1.0e7;
	_g[6] = -x4;
	_g[7] = x4-20;
	_g[8] = -1-x5;
	_g[9] = x5-1;
	_g[10] = -x6;
	_g[11] = x6-2.0e8;
	return;
}
