/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 7;
	int m = 4;
	int p = 0;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 1;
	x[1] = 1;
	x[2] = 1;
	x[3] = 0.50974;
	x[4] = 0.50974;
	x[5] = 0.50974;
	x[6] = 0.98511;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x4 = _x[3];
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x7 = _x[6];
	double x6 = _x[5];
	double x5 = _x[4];
	_f[0] = 0.0;
	_f[0] = -x1*x2*x3;
	_h[0] = x1-4.2*sin(x4)*sin(x4);
	_h[1] = x2-4.2*sin(x5)*sin(x5);
	_h[2] = x3-4.2*sin(x6)*sin(x6);
	_h[3] = x1+2*x2+2*x3-7.2*sin(x7)*sin(x7);
	return;
}
