/*  This file was automatically generated by ParamOptToC  */

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "snlp.h"

void fhg(double *_x, double *_f, double *_h, double *_g);

int main() {
	double *x = NULL;
SNLP s;
int exit_code, i;	int n = 9;
	int m = 6;
	int p = 8;
	x = (double *)calloc(n, sizeof(double));
	x[0] = 0.8;
	x[1] = 0.8;
	x[2] = 0.2;
	x[3] = 0.2;
	x[4] = 1.0454;
	x[5] = 1.0454;
	x[6] = 0;
	x[7] = 0;
	x[8] = 0;
	s = SNLPNew(n, m, p, fhg);
	s->tolerance = 1.0e-6;
	s->maximum_iterations = 500;
	s->show_progress = 1;
	exit_code = SNLPL1SQP(s, x);
	printf("x: ");
	for (i = 0; i < n; i++) {
		printf("%e ", x[i]);
	}
	printf("\n");
	SNLPDelete(s);
	free(x);
	return exit_code;
}
void fhg(double *_x, double *_f, double *_h, double *_g) {
	double x3 = _x[2];
	double x2 = _x[1];
	double x1 = _x[0];
	double x9 = _x[8];
	double x8 = _x[7];
	double x7 = _x[6];
	double x6 = _x[5];
	double x5 = _x[4];
	double x4 = _x[3];
		double d;
		double c;
	_f[0] = 0.0;
		c = (48.4/50.176)*sin(0.25);
		d = (48.4/50.176)*cos(0.25);
	_f[0] = 3000.0*x1+1000.0*x1*x1*x1+2000.0*x2+2000.0*x2*x2*x2/3.0;
	_h[0] = 0.4-x1+2.0*c*x5*x5-x5*x6*(d*sin(x8)+c*cos(x8))-x5*x7*(d*sin(x9)+c*cos(x9));
	_h[1] = 0.4-x2+2.0*c*x6*x6+x5*x6*(d*sin(x8)-c*cos(x8))+x6*x7*(d*sin(x8-x9)-c*cos(x8-x9));
	_h[2] = 0.8+2.0*c*x7*x7+x5*x7*(d*sin(x9)-c*cos(x9))-x6*x7*(d*sin(x8-x9)+c*cos(x8-x9));
	_h[3] = 0.2-x3+2.0*d*x5*x5+x5*x6*(c*sin(x8)-d*cos(x8))+x5*x7*(c*sin(x9)-d*cos(x9));
	_h[4] = 0.2-x4+2.0*d*x6*x6-x5*x6*(c*sin(x8)+d*cos(x8))-x6*x7*(c*sin(x8-x9)+d*cos(x8-x9));
	_h[5] = -0.337+2.0*d*x7*x7-x5*x7*(c*sin(x9)+d*cos(x9))+x6*x7*(c*sin(x8-x9)-d*cos(x8-x9));
	_g[0] = -x1;
	_g[1] = -x2;
	_g[2] = 0.90909-x5;
	_g[3] = x5-1.0909;
	_g[4] = 0.90909-x6;
	_g[5] = x6-1.0909;
	_g[6] = 0.90909-x7;
	_g[7] = x7-1.0909;
	return;
}
